name: Run with Telemetry

description: >
  Execute a command on the runner and export the associated OpenTelemetry
  trace. This action is cross-platform compatible across Linux, macOS, and Windows.
  It is designed to work optimally with the OpenTelemetry Collector,
  GitHub Actions Event Receiver, aligning the telemetry within steps to what
  the receiver emits. This action also injects OTEL-* environment variables
  into the shell, enabling further configuration of the OpenTelemetry
  instrumentation.

author: Kristof Kowalski

inputs:
  github-token:
    required: true
    default: ${{ github.token }}
    description: A token that can be used with the GitHub API.
  github-api-url:
    required: false
    description: Base URL to the GitHub API - if you have an enterprise instance.
  job-as-parent:
    required: false
    default: false
    description: >
      Use the job name as the trace parent. This is useful when you want to
      correlate the trace with the job.
  job-name:
    required: false
    description: >
      The name of the GitHub Actions job.
  otel-exporter-otlp-endpoint:
    required: true
    description: >
      A base endpoint URL for any signal type, with an optionally-specified
      port number.
  otel-exporter-otlp-headers:
    required: false
    description: >
      Headers to attach to outgoing the OTLP gRPC exporter. Set via comma
      separated values; header1=value1,header2=value2.
  otel-resource-attributes:
    required: false
    description: >
      Key-value pairs to be used as resource attributes. Set via comma
      seperated values; key1=value1,key2=value2
  otel-service-name:
    required: true
    description: >
      Logical name of the service. Sets the value of the service.name resource
      attribute.
  run:
    required: true
    description: >
      The command to run.
  shell:
    required: false
    default: bash
    description: >
      You can override the default shell settings in the runner's operating
      system using the shell keyword. Supported options are bash, pwsh,
      python, sh, cmd, pwsh and powershell. The default is bash.
  stderr-as-info:
    required: false
    default: false
    description: >
      If set to 'true', logs stderr as informational messages instead of errors.
      Useful for commands that use stderr for standard output.
  step-name:
    required: true
    description: >
      The name of the step.

outputs:
  trace-id:
    description: >
      The Trace ID generated for the OpenTelemetry trace.
  job-name:
    description: >
      The name of the GitHub Actions job.

runs:
  using: node20
  main: index.js

branding:
  icon: person-running
  color: gray-dark
